version: '3.3'
 
services:
    apache_img:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con
        build:
            context: ./apache
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
        volumes:
            - ../logs/apache:${APACHE_ROOT_DIR}/logs
        ports:
            - ${APACHE_EXPOSED_PORT}:80
        networks:
            public_net:
                ipv4_address: ${APACHE_IP}
        environment:
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
            - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
            - PHP_IP=${PHP_IP}
            - PHP_APP_DIR=${PHP_APP_DIR}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
    mysql_img:
        container_name: mysql_con
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'root'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
        # <Port exposed> : <MySQL Port running inside container>
        - '3306:3306'
        expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
        volumes:
        - my-db:/var/lib/mysql
        networks:
            public_net:
                ipv4_address: ${MYSQL_IP}
    php_img:
        container_name: ${COMPOSE_PROJECT_NAME}_php_con
        build:
            context: ./php
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        working_dir: ${PHP_APP_DIR}
        volumes:
            - ..:${PHP_APP_DIR}
            - ../logs/php:${PHP_ROOT_DIR}/logs
        depends_on:
            - apache_img
            - mysql_img
        networks:
            public_net:
                ipv4_address: ${PHP_IP}
        environment:
            - PHP_ROOT_DIR=${PHP_ROOT_DIR}
            - APACHE_IP=${APACHE_IP}
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
            - MYSQL_IP=${MYSQL_IP}
            - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
volumes:
  my-db:

networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}